<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AR.Drone.Data\AR.Drone.Data.csproj" />
      <ProjectReference Include="..\AR.Drone.Infrastructure\AR.Drone.Infrastructure.csproj" />
    </ItemGroup>

</Project>
